#!/bin/bash
# reporting-engine-v2.sh — Generate daily/weekly/monthly reports for the AI CMO
# Usage: ./reporting-engine-v2.sh [--dry-run] [--type daily|weekly|monthly]
# Reads: All logs, queues, approvals, exports
# Writes: reports/daily/, weekly/, monthly/

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$SCRIPT_DIR/date-context.sh"
QUEUES_DIR="$WORKSPACE_ROOT/queues"
APPROVALS_DIR="$WORKSPACE_ROOT/approvals"
LOGS_DIR="$WORKSPACE_ROOT/logs"
REPORTS_DIR="$WORKSPACE_ROOT/reports"
EXPORTS_DIR="$WORKSPACE_ROOT/ExportsLogs"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE_TAG=$(date '+%Y-%m-%d')

REPORT_TYPE="daily"
DRY_RUN=false

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=true ;;
        --type) REPORT_TYPE="$2"; shift ;;
    esac
    shift
done

# Count files in a directory
count_files() {
    local DIR="$1"
    local PATTERN="${2:-*.md}"
    find "$DIR" -maxdepth 1 -type f -name "$PATTERN" 2>/dev/null | wc -l | tr -d ' '
}

# Count files matching date pattern
count_today_files() {
    local DIR="$1"
    find "$DIR" -maxdepth 1 -type f -name "*$DATE_TAG*" 2>/dev/null | wc -l | tr -d ' '
}

generate_daily_report() {
    local REPORT_FILE="$REPORTS_DIR/daily/daily-report-$DATE_TAG.md"

    # Gather stats
    local INTAKE_NEW=$(grep -c "CLASSIFYING" "$LOGS_DIR/intake-processor.log" 2>/dev/null || echo 0)
    local CONTENT_PRODUCED=$(grep -c "PRODUCED:" "$LOGS_DIR/content-agent.log" 2>/dev/null || echo 0)

    local TOTAL_PENDING=0
    local TOTAL_APPROVED=0
    for CH_DIR in "$QUEUES_DIR"/*/; do
        [ -d "$CH_DIR" ] || continue
        TOTAL_PENDING=$((TOTAL_PENDING + $(count_files "${CH_DIR}pending" 2>/dev/null)))
        TOTAL_APPROVED=$((TOTAL_APPROVED + $(count_files "${CH_DIR}approved" 2>/dev/null)))
    done

    local REVIEW_COUNT=$(count_files "$APPROVALS_DIR/review")
    local BLOCKED_COUNT=$(count_files "$APPROVALS_DIR/blocked")
    local POSTED_COUNT=$(count_files "$EXPORTS_DIR/posted")

    # Gather per-channel stats
    local CHANNEL_STATS=""
    for CH_DIR in "$QUEUES_DIR"/*/; do
        [ -d "$CH_DIR" ] || continue
        local CH=$(basename "$CH_DIR")
        local CH_PENDING=$(count_files "${CH_DIR}pending")
        local CH_APPROVED=$(count_files "${CH_DIR}approved")
        CHANNEL_STATS="$CHANNEL_STATS| $CH | $CH_PENDING | $CH_APPROVED |\n"
    done

    if [ "$DRY_RUN" = true ]; then
        echo "[DRY RUN] Would write daily report to $REPORT_FILE"
        return
    fi

    cat > "$REPORT_FILE" <<EOF
# Daily CMO Report — $DATE_TAG

**Generated:** $TIMESTAMP
**Type:** Daily Pipeline Report

---

## Pipeline Summary

| Metric | Count |
|---|---|
| New source material processed | $INTAKE_NEW |
| Content pieces produced | $CONTENT_PRODUCED |
| Items pending approval | $TOTAL_PENDING |
| Items approved | $TOTAL_APPROVED |
| Items in review queue | $REVIEW_COUNT |
| Items blocked | $BLOCKED_COUNT |
| Items distributed/posted | $POSTED_COUNT |

## Per-Channel Queue Status

| Channel | Pending | Approved |
|---|---|---|
$(echo -e "$CHANNEL_STATS")

## Review Queue

Items requiring human review:

$(ls -1 "$APPROVALS_DIR/review/" 2>/dev/null | head -10 | while read f; do echo "- $f"; done)
$([ $(count_files "$APPROVALS_DIR/review") -eq 0 ] && echo "- (none)")

## Blocked Items

Items blocked today:

$(ls -1 "$APPROVALS_DIR/blocked/" 2>/dev/null | grep "$DATE_TAG" | head -10 | while read f; do echo "- $f"; done)
$([ -z "$(ls "$APPROVALS_DIR/blocked/" 2>/dev/null | grep "$DATE_TAG")" ] && echo "- (none)")

## Logs

- Intake log: \`$LOGS_DIR/intake-processor.log\`
- Content log: \`$LOGS_DIR/content-agent.log\`
- Approval log: \`$LOGS_DIR/approval-engine.log\`
- Distribution log: \`$LOGS_DIR/distribution-engine.log\`
- Pipeline log: \`$LOGS_DIR/daily-pipeline.log\`

## Next Actions

1. Review items in \`approvals/review/\` if any
2. Check blocked items for false positives
3. Add new source material to \`data/source-notes/\` or \`source-links/\`
4. Run \`daily-pipeline.sh\` again tomorrow

---
*Generated by OpenClaw AI CMO Reporting Engine*
EOF

    echo "Daily report written to: $REPORT_FILE"
}

generate_weekly_report() {
    local REPORT_FILE="$REPORTS_DIR/weekly/weekly-report-$DATE_TAG.md"

    if [ "$DRY_RUN" = true ]; then
        echo "[DRY RUN] Would write weekly report to $REPORT_FILE"
        return
    fi

    # Count files from the past 7 days across key folders
    local WEEK_PRODUCED=$(find "$WORKSPACE_ROOT/data" -type f -name "*.md" -newer "$REPORTS_DIR/weekly/" -mtime -7 2>/dev/null | wc -l | tr -d ' ')
    local WEEK_POSTED=$(find "$EXPORTS_DIR/posted" -type f -mtime -7 2>/dev/null | wc -l | tr -d ' ')
    local WEEK_BLOCKED=$(find "$APPROVALS_DIR/blocked" -type f -mtime -7 2>/dev/null | wc -l | tr -d ' ')
    local DAILY_REPORTS=$(find "$REPORTS_DIR/daily" -type f -mtime -7 2>/dev/null | wc -l | tr -d ' ')

    cat > "$REPORT_FILE" <<EOF
# Weekly CMO Report — Week of $DATE_TAG

**Generated:** $TIMESTAMP
**Type:** Weekly Summary

---

## Week Overview

| Metric | Count |
|---|---|
| Content pieces produced | $WEEK_PRODUCED |
| Items distributed/posted | $WEEK_POSTED |
| Items blocked | $WEEK_BLOCKED |
| Daily reports generated | $DAILY_REPORTS |

## Content Produced This Week

$(find "$WORKSPACE_ROOT/data" -type f -name "*.md" -mtime -7 2>/dev/null | head -20 | while read f; do echo "- $(basename "$f")"; done)

## Items Posted This Week

$(find "$EXPORTS_DIR/posted" -type f -mtime -7 2>/dev/null | head -20 | while read f; do echo "- $(basename "$f")"; done)

## Review Queue Status

$(ls -1 "$APPROVALS_DIR/review/" 2>/dev/null | head -10 | while read f; do echo "- $f"; done)
$([ $(count_files "$APPROVALS_DIR/review") -eq 0 ] && echo "- (none)")

## Next Week Priorities

1. Process any items remaining in review queue
2. Add fresh source material
3. Consider weekly roundup post
4. Check if newsletter draft is ready

---
*Generated by OpenClaw AI CMO Reporting Engine*
EOF

    echo "Weekly report written to: $REPORT_FILE"
}

generate_monthly_report() {
    local REPORT_FILE="$REPORTS_DIR/monthly/monthly-report-$DATE_TAG.md"

    if [ "$DRY_RUN" = true ]; then
        echo "[DRY RUN] Would write monthly report to $REPORT_FILE"
        return
    fi

    local MONTH_PRODUCED=$(find "$WORKSPACE_ROOT/data" -type f -name "*.md" -mtime -30 2>/dev/null | wc -l | tr -d ' ')
    local MONTH_POSTED=$(find "$EXPORTS_DIR/posted" -type f -mtime -30 2>/dev/null | wc -l | tr -d ' ')
    local MONTH_BLOCKED=$(find "$APPROVALS_DIR/blocked" -type f -mtime -30 2>/dev/null | wc -l | tr -d ' ')

    cat > "$REPORT_FILE" <<EOF
# Monthly CMO Report — $DATE_TAG

**Generated:** $TIMESTAMP
**Type:** Monthly Summary

---

## Month Overview

| Metric | Count |
|---|---|
| Total content produced | $MONTH_PRODUCED |
| Total items posted | $MONTH_POSTED |
| Total items blocked | $MONTH_BLOCKED |

## Channel Distribution

$(for CH_DIR in "$QUEUES_DIR"/*/; do
    CH=$(basename "$CH_DIR")
    POSTED=$(find "$EXPORTS_DIR/posted" -name "*$CH*" -mtime -30 2>/dev/null | wc -l | tr -d ' ')
    echo "- **$CH**: $POSTED items"
done)

## Recommendations

1. Review content pillars — are they still relevant?
2. Check SEO topic opportunities
3. Update campaign themes for next month
4. Archive old queue items
5. Review blocked items for pattern insights

---
*Generated by OpenClaw AI CMO Reporting Engine*
EOF

    echo "Monthly report written to: $REPORT_FILE"
}

echo "Generating $REPORT_TYPE report..."

case "$REPORT_TYPE" in
    daily) generate_daily_report ;;
    weekly) generate_weekly_report ;;
    monthly) generate_monthly_report ;;
    *) echo "Unknown report type: $REPORT_TYPE. Use: daily, weekly, or monthly" ;;
esac
